### ISSUE TITLE
How do I use this? :|

### ISSUE THREAD

**Issue by sardaukar** [ripienaar/rotrep#1]
I've installed go. Now what? :D 

A binary release would be great, too.

**Comment by ripienaar** [comment]
doh I was not subscribed to this repo so did not get your issue mail sorry about that :)

Yeah I was thinking of a binary release but the go binary release tool sucked, I opened a ticket and they made it not suck, so I should do that.

thanks! if you have a specific OS and architecture tell me and I make you a binary quick

**Comment by sardaukar** [comment]
I'm on Linux amd64 on my NAS (where I'd like to use this). Thanks!

**Comment by ripienaar** [comment]
@sardaukar check out https://github.com/ripienaar/rotrep/releases/tag/v0.0.1 let me know how that goes

**Comment by sardaukar** [comment]
@ripienaar will do later when I get home. Cheers

**Comment by sardaukar** [comment]
(Sorry for the delay) tried this out, pretty straightforward to do cron jobs and the like. Thanks! And for the binary release too! :D
